### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by luomingyang1999** [fwq7/MyBlog#2]
hi：
    good evening！
could u send me your sql file？

**Comment by fwq7** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fwq7/MyBlog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 晚上10:41
收件人:&nbsp;"fwq7/MyBlog"<MyBlog@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fwq7/MyBlog] sql文件 (#2)





 
hi：
 good evening！
 could u send me your sql file？

**Comment by fwq7** [comment]
已上传
